const fs = require('fs');
const vm = require('vm');
const assert = require('assert/strict');
const read = p => fs.readFileSync(p, 'utf8');
const engine = read('content/auto-engine.js');
const summaryCode = engine.slice(engine.indexOf('  function summary()'), engine.indexOf('  function applyConfig('));
let now = 10000;
const media = { muted: false, volume: 1 };
const entry = { media, mode: 'process', state: { signalTickCount: 10, signalActive: false }, lastStateAt: 9900, lastSignalAt: 5000 };
const sandbox = { entries: new Map([[media, entry]]), blockedReasons: new Map(), config: {}, context: {state:'running'}, contextSuspendedForGesture: false, engineFailure: '', chrome: {runtime:{getManifest:()=>({version:'test'})}}, Date:{now:()=>now}, finite:(v,f=0)=>Number.isFinite(Number(v))?Number(v):f, isAudible:()=>true };
vm.createContext(sandbox); vm.runInContext(summaryCode, sandbox);
assert.equal(sandbox.summary().lastSignalAgeMs, 5000, 'silent state reports must not refresh signal age');
entry.state.signalActive = true;
assert.equal(sandbox.summary().lastSignalAgeMs, 5000, 'stale active report must not stay fresh forever');
entry.lastSignalAt = 9900;
assert.equal(sandbox.summary().lastSignalAgeMs, 100);
// Two audible players: a hidden silent preload with the newest state message must not outrank the one carrying signal.
const hidden = { muted: false, volume: 1 };
const silent = { media: hidden, mode: 'process', state: { signalTickCount: 3, signalActive: false }, lastStateAt: 9990, lastSignalAt: null };
entry.state = { signalTickCount: 50, signalActive: true, lastInputDb: -20 }; entry.lastStateAt = 9500; entry.lastSignalAt = 9500;
sandbox.entries.set(hidden, silent);
assert.equal(sandbox.summary().lastSignalAgeMs, 500, 'player with signal outranks a newer silent hidden player');
assert.equal(sandbox.summary().signalTickCount, 50);
sandbox.entries.delete(hidden);
console.log('PASS signal-carrying player is the primary on multi-video pages');
const popup = read('popup/index.js');
const fn = popup.slice(popup.indexOf('function shouldAutoStartCapture('), popup.indexOf('async function maybeAutoStartCapture('));
const ctx = { autoCaptureAttempted:false, autoCaptureRunning:false, settings:{enabled:true}, activeTabId:1, activeTabUrl:'https://example.com', finiteNumber:(v,f=0)=>Number.isFinite(Number(v))?Number(v):f };
vm.createContext(ctx); vm.runInContext(fn,ctx);
const base = { autoActive:true, tabAudibleHint:true, signalTickCount:0, lastSignalAgeMs:null, auto:{responding:true} };
assert.equal(ctx.shouldAutoStartCapture(base), true, 'audible tab with no automatic signal needs capture fallback');
assert.equal(ctx.shouldAutoStartCapture({...base,tabAudibleHint:false}),false, 'silence alone must not trigger capture');
assert.equal(ctx.shouldAutoStartCapture({...base,signalTickCount:5,lastSignalAgeMs:100}),false);
assert.equal(ctx.shouldAutoStartCapture({...base,playerMuted:true}),false);
assert.equal(ctx.shouldAutoStartCapture({...base,captureActive:true}),false);
console.log('PASS automatic signal freshness and audible-tab capture recovery');
const render = popup.slice(popup.indexOf('function renderStatus('), popup.indexOf('\nbind();', popup.indexOf('function renderStatus(')));
Object.assign(ctx, {renderAutoSite:()=>{}, setReadouts:()=>{}, setStrengthControlsEnabled:()=>{},setReloadVisible:()=>{},setNotices:()=>{},setEffect:()=>{},setCaptureVisible:(available,active)=>{ctx.captureVisible=available&&!active;},setHeadline:value=>{ctx.headline=value;},t:key=>key});
vm.runInContext(render,ctx);
ctx.renderStatus(base);
assert.equal(ctx.captureVisible,true,'unconfirmed automatic graph must expose recovery');
assert.notEqual(ctx.headline.label,'statusConnected');
console.log('PASS unconfirmed graph does not claim connected and exposes recovery');
